name: unit-tests

on: push

jobs:
  unit-tests:
    name: Run PyTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout
      - name: Lint
        uses: github/super-linter
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
